### PR TITLE
Rework icon sys

### PR DESCRIPTION
**Pull request by badgamerbad**
1. added the grid to select the icon
2. modified HTML CSS structure to categorize icons
3. used SASS to modify style.css 
4. added scripts in package.json, please run "npm run dev"

### CODE REVIEW

**Comment by badgamerbad** [comment]
i have used same svgs just for test purpose, we will just have to replace the svg element content to reflect new icon.
i ll fix the border issue

**Comment by badgamerbad** [comment]
i need more info on formatting issue though. i have changed the px units to em units for responsiveness

**Comment by maticbasle** [comment]
There are changes done to the formatting of HTML (indentation of tags) in the index.html file in the "added grid icon selection" commit (possibly elsewhere, just noticed this one because of the amount of changes). 

Could you create a new PR, with the current master as the base and add your changes to that, without changing any of the formattings and without test SVGs? And also include changes from #16 in the same PR?

Example of the formatting change: 
screenshot 2018-10-23 at 17 09 25

**Comment by badgamerbad** [comment]
okay ill create a new PR and merge all the code from #16 as well.

**Comment by maticbasle** [comment]
#17

**Pull request closed without merging**
